name: Test vol-tests on Ubuntu

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout hdf-spack
      uses: actions/checkout@v2
      with:
        repository: HDFGroup/hdf-spack
        path: ./hdf-spack
      
    - name: Checkout spack
      uses: actions/checkout@v2
      with:
        repository: spack/spack
        path: ./spack

    - name: Run a multi-line script
      run: |
        . ./spack/share/spack/setup-env.sh
        spack repo add .
        spack repo list
        spack install --test root hdf5-vol-tests+vol-external-passthrough
        
